/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "uart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include <string.h>
#include "uart.h"

int main(void)
{
    char buffer[128];
    int index = 0;
    char ch;

    UartInit(9600);
    UartPuts("GPS Test Started...\r\n");
    UartPuts("Waiting for NMEA sentences...\r\n");

    while (1)
    {
        ch = UartGetch();  // Read one byte from GPS (PA3)

        if (ch == '\n')    // End of NMEA line
        {
            buffer[index] = '\0';

            UartPuts("GPS: ");
            UartPuts(buffer);
            UartPuts("\r\n");

            index = 0;
            DelayMs(1000);
        }
        else
        {
            if (index < sizeof(buffer) - 1)
                buffer[index++] = ch;
        }
    }
}



